import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Navbar from "../components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Filtro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <form action="" className={styles.container}>
          <Link href="/moda">
            <input className={styles.inputBtn} type="radio" id="valueIs-1" name="valueIs-radio" value="valueIs-1" />
            <label className={styles.neonBtn} htmlFor="valueIs-1">
              <span className={styles.span}></span>
              <span className={styles.txt}>Moda</span>
            </label>
          </Link>
          <Link href="/media">
            <input className={styles.inputBtn} type="radio" id="valueIs-2" name="valueIs-radio" value="valueIs-2" />
            <label className={styles.neonBtn} htmlFor="valueIs-2">
              <span className={styles.span}></span>
              <span className={styles.txt}>Média</span>
            </label>
          </Link>
          <Link href="/mediana">
            <input className={styles.inputBtn} type="radio" id="valueIs-2" name="valueIs-radio" value="valueIs-2" />
            <label className={styles.neonBtn} htmlFor="valueIs-2">
              <span className={styles.span}></span>
              <span className={styles.txt}>Mediana</span>
            </label>
          </Link>
          <Link href="/passa-alta">
            <input className={styles.inputBtn} type="radio" id="valueIs-2" name="valueIs-radio" value="valueIs-2" />
            <label className={styles.neonBtn} htmlFor="valueIs-2">
              <span className={styles.span}></span>
              <span className={styles.txt}>Passa Alta</span>
            </label>
          </Link>
          <Link href="/logicas">
            <input className={styles.inputBtn} type="radio" id="valueIs-2" name="valueIs-radio" value="valueIs-2" />
            <label className={styles.neonBtn} htmlFor="valueIs-2">
              <span className={styles.span}></span>
              <span className={styles.txt}>Ope. lógico</span>
            </label>
          </Link>
        </form>
    </>
  );
}
